name: Run RAG Experiment

on:
  push:
    paths:
      - '**.py'
      - 'config.yaml'

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

    - name: Run main script
      run: python main.py

    - name: Notify Slack
      run: |
        python -c "from notify import notify_slack; notify_slack('✅ Llama3 + RAG実験完了 (GitHub Actions)')"
