name: CI with Tests

on:
  push:
    paths:
      - '**.py'
      - 'config.yaml'

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model tests
      run: |
        python tests/test_model.py

    - name: Run main experiment
      run: |
        python main.py

    - name: Notify Slack
      if: always()
      run: |
        python -c "from notify import notify_slack; notify_slack('✅ 実験とテストが完了しました')"
